


/*USING BSSR - BIT SET AND RESET REGISTER OF GPIO TURN ON AND OFF LED */
#include "stm32f4xx.h"
#include <stdint.h>

#define GPIOAEN  (1U<<0)
#define PIN5	 (1U<<5)
#define LED_PIN	  PIN5

int main(void)
{

RCC->AHB1ENR |=GPIOAEN;
GPIOA->MODER |=(1U<<10);
GPIOA->MODER &=~(1U<<11);



	while (1)
	{
		GPIOA->BSRR =LED_PIN;
		for (int i=0; i<10000;i++) {}

		GPIOA->BSRR =(1U<<21);
		for (int i=0; i<10000;i++) {}
	}
}

/*
 * LEARNING SUMMARY
 * BSRR , ODR, MODER REGISTERS
 * MODER- TO SET AS INPUT AND OUTPUT
 * ODR - IF OUTPUT THEN OUTPUT DATA REGISTER
 * BSSR - BIT SET AND RESET REGISTER BY WRITING 1 TO RESPECTIVE PIN TO TURN ON AND OFF
 *
 */
