


/*  SET AS INPUT BY ADDING A PUSH BUTTON
 * 	BASED ON DATA SHEET PUSH BUTTON IS CONNECTED TO PC13
 * 	PORT=C
 * 	PIN=13
*/

/*
 * GPIOC is also connected to AHB1 BUS
 * SO IN AHB1EN REGISTER NEED TO ENABLE GPIOC
 */
#include "stm32f4xx.h"
#include <stdint.h>

#define GPIOAEN  		(1U<<0)
#define GPIOCEN  		(1U<<2)

#define PIN5	 		(1U<<5)
#define PIN13	 		(1U<<13)
#define LED_PIN	  		PIN5
#define Push_Button	  	PIN13

int main(void)
{

RCC->AHB1ENR |=GPIOAEN;
RCC->AHB1ENR |=GPIOCEN;

GPIOA->MODER |=(1U<<10);  // SET AS OUTPUT MODE FOR PUSH BUTTON
GPIOA->MODER &=~(1U<<11); // SET AS OUTPUT MODE FOR PUSH BUTTON

GPIOC->MODER &=~(1U<<26); // SET AS INPUT MODE FOR PUSH BUTTON
GPIOC->MODER &=~(1U<<27); // SET AS INPUT MODE FOR PUSH BUTTON

	while (1)
	{
		if (GPIOC->IDR & Push_Button)    // IF PIN 13 IS active in INPUT REGISTER
		{
			GPIOA->BSRR =LED_PIN;
		}
		else
		{
		GPIOA->BSRR =(1U<<21);
		}
	}
}

/*
 * LEARNING SUMMARY
 * BSRR , ODR, MODER REGISTERS
 * MODER- TO SET AS INPUT AND OUTPUT
 * ODR - IF OUTPUT THEN OUTPUT DATA REGISTER
 * BSSR - BIT SET AND RESET REGISTER BY WRITING 1 TO RESPECTIVE PIN TO TURN ON AND OFF
 * IDR - INPUT DATA REGISTER
 */
